- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  - include_tasks: test/integration/targets/aci_rest/tasks/main.yml
    tags: aci_rest
  - include_tasks: test/integration/targets/aci_ap/tasks/main.yml
    tags: aci_ap
  - include_tasks: test/integration/targets/aci_bd/tasks/main.yml
    tags: aci_bd
  - include_tasks: test/integration/targets/aci_bd_subnet/tasks/main.yml
    tags: aci_bd_subnet
  - include_tasks: test/integration/targets/aci_config_rollback/tasks/main.yml
    tags: aci_config_rollback
  - include_tasks: test/integration/targets/aci_config_snapshot/tasks/main.yml
    tags: aci_config_snapshot
  - include_tasks: test/integration/targets/aci_contract/tasks/main.yml
    tags: aci_contract
  - include_tasks: test/integration/targets/aci_contract_subject/tasks/main.yml
    tags: aci_contract_subject
  - include_tasks: test/integration/targets/aci_contract_subject_to_filter/tasks/main.yml
    tags: aci_contract_subject_to_filter
  - include_tasks: test/integration/targets/aci_epg/tasks/main.yml
    tags: aci_epg
  - include_tasks: test/integration/targets/aci_epg_to_contract/tasks/main.yml
    tags: aci_epg_to_contract
  - include_tasks: test/integration/targets/aci_epg_to_domain/tasks/main.yml
    tags: aci_epg_to_domain
  - include_tasks: test/integration/targets/aci_filter/tasks/main.yml
    tags: aci_filter
  - include_tasks: test/integration/targets/aci_filter_entry/tasks/main.yml
    tags: aci_filter_entry
  - include_tasks: test/integration/targets/aci_tenant/tasks/main.yml
    tags: aci_tenant
  - include_tasks: test/integration/targets/aci_vrf/tasks/main.yml
    tags: aci_vrf
